package ru.test.async;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * WSDL File for HelloService
 *
 * This class was generated by Apache CXF 3.2.2
 * 2018-04-25T15:12:24.232+03:00
 * Generated source version: 3.2.2
 *
 */
@WebServiceClient(name = "AsyncHello_Service",
                  wsdlLocation = "file:example.wsdl",
                  targetNamespace = "http://async.test.ru/")
public class AsyncHelloService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://async.test.ru/", "AsyncHello_Service");
    public final static QName AsyncHelloPortType = new QName("http://async.test.ru/", "AsyncHello_PortType");
    static {
        URL url = null;
        try {
            url = new URL("file:example.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AsyncHelloService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:example.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AsyncHelloService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AsyncHelloService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AsyncHelloService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public AsyncHelloService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public AsyncHelloService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public AsyncHelloService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns AsyncHelloPortType
     */
    @WebEndpoint(name = "AsyncHello_PortType")
    public AsyncHelloPortType getAsyncHelloPortType() {
        return super.getPort(AsyncHelloPortType, AsyncHelloPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AsyncHelloPortType
     */
    @WebEndpoint(name = "AsyncHello_PortType")
    public AsyncHelloPortType getAsyncHelloPortType(WebServiceFeature... features) {
        return super.getPort(AsyncHelloPortType, AsyncHelloPortType.class, features);
    }

}
